name: Update Hummingbird Community Packages

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    strategy:
        matrix:
          repo:
            - dummy
    steps:
    - name: App Token
      uses: tibdex/github-app-token@v2
      id: generate-token
      with:
        app_id: ${{ secrets.HB_APP_ID }}
        private_key: ${{ secrets.HB_APP_PRIVATE_KEY }}
    - name: Checkout Project Template
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        path: project-template
    - name: Checkout Target Repository
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 1
        path: ${{ matrix.repo }}
        repository: hummingbird-community/${{ matrix.repo }}
    - name: Install Dependencies
      run: |
        brew install mint
        mint install hummingbird-project/swift-mustache-cli
        echo "$HOME/.mint/bin" >> $GITHUB_PATH
    - name: Update Target Repository
      run: |
        cd project-template
        ./update.sh ../${{ matrix.repo }}
    - name: Commit message
      run: |
        git log -1 >> $GIT_COMMIT_MESSAGE
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ steps.generate-token.outputs.token }}
        path: ${{ matrix.repo }}
        commit-message: 'Update from hummingbird-community-template ${{ github.sha }}'
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: project-template-update
        title: 'Update from Hummingbird Project Template'
        body: '$GIT_COMMIT_MESSAGE\nAutomated update of files from https://github.com/hummingbird-community/hummingbird-community-template'
        base: main
